/*
 * MainAbout.java
 * Copyright 2001 (C) Tom Epperly <tomepperly@home.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * Created on April 26, 2001, 10:47 PM
 */

package pcgen.gui;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Create a simple panel to identify the program and those who contributed
 * to it.
 *
 * @author  Tom Epperly <tomepperly@home.com>
 * @version $Revision: 1.1 $
 */
public final class MainAbout extends javax.swing.JPanel
{

	private javax.swing.JLabel d_versionLabel;
	private javax.swing.JLabel d_dateLabel;
	private javax.swing.JLabel d_leaderLabel;
	private javax.swing.JLabel d_helperLabel;
	private javax.swing.JLabel d_wwwLink;
	private javax.swing.JLabel d_emailLabel;
	private javax.swing.JTextField d_version;
	private javax.swing.JTextField d_releaseDate;
	private javax.swing.JTextField d_projectLead;
	private javax.swing.JTextField d_wwwSite;
	private javax.swing.JTextField d_mailingList;
	private javax.swing.JLabel d_licenseLabel;
	private javax.swing.JTextField d_licenseText;
	private javax.swing.JLabel d_testLabel;
	private javax.swing.JScrollPane d_developerArea;
	private javax.swing.JTextArea d_developerList;
	private javax.swing.JScrollPane d_testArea;
	private javax.swing.JTextArea d_testMonkeys;
	private javax.swing.JScrollPane d_licenseArea;
	private javax.swing.JTextArea d_LGPL;
	private ResourceBundle d_properties;

	/** Creates new form MainAbout */
	public MainAbout()
	{
		try
		{
			try
			{
				d_properties = ResourceBundle.getBundle("pcgen/gui/PCGenProp");
			}
			catch (java.util.MissingResourceException mre)
			{
				d_properties = null;
			}
			initComponents();
		}
		finally
		{
			d_properties = null;
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()
	{
		d_versionLabel = new javax.swing.JLabel();
		d_dateLabel = new javax.swing.JLabel();
		d_leaderLabel = new javax.swing.JLabel();
		d_helperLabel = new javax.swing.JLabel();
		d_wwwLink = new javax.swing.JLabel();
		d_emailLabel = new javax.swing.JLabel();
		d_version = new javax.swing.JTextField();
		d_releaseDate = new javax.swing.JTextField();
		d_projectLead = new javax.swing.JTextField();
		d_wwwSite = new javax.swing.JTextField();
		d_mailingList = new javax.swing.JTextField();
		d_licenseLabel = new javax.swing.JLabel();
		d_licenseText = new javax.swing.JTextField();
		d_testLabel = new javax.swing.JLabel();
		d_developerArea = new javax.swing.JScrollPane();
		d_developerList = new javax.swing.JTextArea();
		d_testArea = new javax.swing.JScrollPane();
		d_testMonkeys = new javax.swing.JTextArea();
		d_licenseArea = new javax.swing.JScrollPane();
		d_LGPL = new javax.swing.JTextArea();

		setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		d_versionLabel.setText("PCGen version:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_versionLabel, gridBagConstraints1);

		d_dateLabel.setText("Release date:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_dateLabel, gridBagConstraints1);

		d_leaderLabel.setText("Chief Code Monkey:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 2;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_leaderLabel, gridBagConstraints1);

		d_helperLabel.setText("Code Monkeys:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 5;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
		add(d_helperLabel, gridBagConstraints1);

		d_wwwLink.setText("WWW site:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 3;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_wwwLink, gridBagConstraints1);

		d_emailLabel.setText("Email list:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 4;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_emailLabel, gridBagConstraints1);

		d_version.setEditable(false);
		d_version.setText("2.0.0-pre");
		d_version.setBorder(null);
		d_version.setOpaque(false);
		if (d_properties != null)
		{
			try
			{
				d_version.setText(d_properties.getString("VersionNumber"));
			}
			catch (MissingResourceException mre)
			{
				d_version.setText("Missing VersionNumber property");
			}
		}
		else
		{
			d_version.setText("Unknown VersionNumber");
		}
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_version, gridBagConstraints1);

		d_releaseDate.setEditable(false);
		d_releaseDate.setText("Unpublished");
		d_releaseDate.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
		d_releaseDate.setOpaque(false);
		if (d_properties != null)
		{
			try
			{
				d_releaseDate.setText(d_properties.getString("ReleaseDate"));
			}
			catch (MissingResourceException mre)
			{
				d_releaseDate.setText("Missing ReleaseDate property");
			}
		}
		else
		{
			d_releaseDate.setText("Missing ReleaseDate");
		}
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_releaseDate, gridBagConstraints1);

		d_projectLead.setEditable(false);
		d_projectLead.setText("Bryan McRoberts");
		d_projectLead.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
		d_projectLead.setOpaque(false);
		if (d_properties != null)
		{
			try
			{
				d_projectLead.setText(d_properties.getString("HeadCodeMonkey"));
			}
			catch (MissingResourceException mre)
			{
				d_projectLead.setText("Bryan McRoberts");
			}
		}
		else
		{
			d_projectLead.setText("Bryan McRoberts");
		}
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 2;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_projectLead, gridBagConstraints1);

		d_wwwSite.setEditable(false);
		d_wwwSite.setText("http://pcgen.sourceforge.net/");
		d_wwwSite.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
		d_wwwSite.setOpaque(false);
		if (d_properties != null)
		{
			try
			{
				d_wwwSite.setText(d_properties.getString("WWWHome"));
			}
			catch (MissingResourceException mre)
			{
				d_wwwSite.setText("http://pcgen.sourceforge.net/");
			}
		}
		else
		{
			d_wwwSite.setText("http://pcgen.sourceforge.net/");
		}
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 3;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_wwwSite, gridBagConstraints1);

		d_mailingList.setEditable(false);
		d_mailingList.setText("http://groups.yahoo.com/group/pcgen");
		d_mailingList.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
		d_mailingList.setOpaque(false);
		if (d_properties != null)
		{
			try
			{
				d_mailingList.setText(d_properties.getString("MailingList"));
			}
			catch (MissingResourceException mre)
			{
				d_mailingList.setText("http://groups.yahoo.com/group/pcgen");
			}
		}
		else
		{
			d_mailingList.setText("http://groups.yahoo.com/group/pcgen");
		}
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 4;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_mailingList, gridBagConstraints1);

		d_licenseLabel.setText("Licensing terms:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 7;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(d_licenseLabel, gridBagConstraints1);

		d_licenseText.setEditable(false);
		d_licenseText.setText("Lesser GNU Public License");
		d_licenseText.setBorder(null);
		d_licenseText.setOpaque(false);
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 7;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_licenseText, gridBagConstraints1);

		d_testLabel.setText("Test Monkeys:");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 6;
		gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
		add(d_testLabel, gridBagConstraints1);

		d_developerList.setWrapStyleWord(true);
		d_developerList.setLineWrap(true);
		d_developerList.setEditable(false);
		if (d_properties != null)
		{
			try
			{
				d_developerList.setText(d_properties.getString("CodeMonkeys"));
			}
			catch (MissingResourceException mre)
			{
				// ignore
			}
		}
		d_developerArea.setViewportView(d_developerList);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 5;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.weightx = 1.0;
		gridBagConstraints1.weighty = 1.0;
		add(d_developerArea, gridBagConstraints1);

		d_testMonkeys.setWrapStyleWord(true);
		d_testMonkeys.setLineWrap(true);
		d_testMonkeys.setEditable(false);
		if (d_properties != null)
		{
			try
			{
				d_testMonkeys.setText(d_properties.getString("TestMonkeys"));
			}
			catch (MissingResourceException mre)
			{
				// ignore
			}
		}
		d_testArea.setViewportView(d_testMonkeys);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 6;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.weightx = 1.0;
		gridBagConstraints1.weighty = 1.0;
		add(d_testArea, gridBagConstraints1);

		d_LGPL.setEditable(false);
		InputStream lgpl = ClassLoader.getSystemResourceAsStream("LICENSE");
		if (lgpl != null)
		{
			try
			{
				d_LGPL.read(new InputStreamReader(lgpl), "LICENSE");
			}
			catch (IOException ioe)
			{
				d_LGPL.setText("Unable to read license text from distribution.");
			}
		}
		else
		{
			d_LGPL.setText("Your distribution does not contain the license text.");
		}
		d_licenseArea.setViewportView(d_LGPL);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 8;
		gridBagConstraints1.gridwidth = 2;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.weightx = 1.0;
		gridBagConstraints1.weighty = 3.0;
		add(d_licenseArea, gridBagConstraints1);

	}
}
