/*
 * DamageDialog.java
 *
 * Created on July 20, 2003, 10:30 AM
 */

package plugin.initiative.gui;

/**
 *
 * @author  soulcatcher
 */
public class DamageDialog extends javax.swing.JDialog {

	/** Creates new form DamageDialog */
	public DamageDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocation(parent.getX() + 100, parent.getY() + 100);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents() {//GEN-BEGIN:initComponents
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    damageField = new javax.swing.JTextField();
    subdualField = new javax.swing.JCheckBox();
    bOK = new javax.swing.JButton();
    bCancel = new javax.swing.JButton();

    getContentPane().setLayout(new java.awt.GridBagLayout());

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    jLabel1.setText("Damage");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    getContentPane().add(jLabel1, gridBagConstraints);

    damageField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        damageFieldActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(damageField, gridBagConstraints);

    subdualField.setText("Subdual");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(subdualField, gridBagConstraints);

    bOK.setText("Ok");
    bOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bOKActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
    getContentPane().add(bOK, gridBagConstraints);

    bCancel.setText("Cancel");
    bCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCancelActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
    getContentPane().add(bCancel, gridBagConstraints);

    pack();
  }//GEN-END:initComponents

	private void damageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageFieldActionPerformed
		try {
			damage = new Integer(damageField.getText()).intValue();
		}
		catch (NumberFormatException e) {
			damage = 0;
			damageField.setText(damage + "");
		}
	}//GEN-LAST:event_damageFieldActionPerformed

	private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
		retVal = 1;
		setVisible(false);
		dispose();
	}//GEN-LAST:event_bCancelActionPerformed

	private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
		try {
			damage = new Integer(damageField.getText()).intValue();
			retVal = 0;
			setVisible(false);
			dispose();
		}
		catch (NumberFormatException e) {
			damage = 0;
			damageField.setText(damage + "");
		}
	}//GEN-LAST:event_bOKActionPerformed

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}//GEN-LAST:event_closeDialog

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		new DamageDialog(new javax.swing.JFrame(), true).show();
	}

	public int getReturn() {
		return retVal;
	}

	public int getDamage() {
		return damage;
	}

	public boolean getSubdual() {
		return subdualField.isSelected();
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox subdualField;
  private javax.swing.JTextField damageField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton bCancel;
  private javax.swing.JButton bOK;
  // End of variables declaration//GEN-END:variables

	private int retVal;
	private int damage;

	public static int OK_VALUE = 0;
	public static int CANCEL_VALUE = 1;
}
