/*
Password Tracker (PATRA). An application to safely store your passwords.
Copyright (C) 2006-2009  Bruno Ranschaert, S.D.I.-Consulting BVBA.

For more information contact: nospam@sdi-consulting.com
Visit our website: http://www.sdi-consulting.com

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

package com.sdi.pws.gui.dialog.about;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.sdi.pws.gui.GuiUtil;
import com.sdi.pws.util.SwinglibUtil;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;

public class About
{
    private JLabel aboutImage;
    private JPanel mainPanel;

    public About()
    {
        aboutImage.setIcon(new ImageIcon(About.class.getClassLoader().getResource("assets/pwt-about.jpg")));
        aboutImage.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent aMouseEvent)
            {
                Desktop lDesktop = Desktop.getDesktop();
                if(lDesktop.isSupported(Desktop.Action.BROWSE))
                {
                    try
                    {
                        lDesktop.browse(new URI("http://www.sdi-consulting.com"));
                    }
                    catch(Exception e)
                    {
                    }

                }
            }
        });
    }

    public static void about(JComponent aApp)
    {
        final About lAbout = new About();
        lAbout.aboutImage.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        final JOptionPane lPane = new JOptionPane(lAbout.mainPanel, JOptionPane.PLAIN_MESSAGE, JOptionPane.DEFAULT_OPTION);

        final JDialog lDialog = lPane.createDialog(aApp, GuiUtil.getText("about.title"));
        SwinglibUtil.processNestedComponents(lDialog, new SwinglibUtil.BackgroundColorChanger(Color.white));
        lDialog.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        aboutImage = new JLabel();
        aboutImage.setIcon(new ImageIcon(getClass().getResource("/assets/pwt-about.jpg")));
        aboutImage.setIconTextGap(0);
        aboutImage.setText("");
        panel1.add(aboutImage, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}