/*
 *  Initiative - A role playing utility to track turns
 *  Copyright (C) 2002 Devon D Jones
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 *  The author of this program grants you the ability to use this code
 *  in conjunction with code that is covered under the Open Gaming License
 *
 * PreferencesDamagePanel.java
 *
 * Created on July 11, 2003, 4:34 PM
 */
package plugin.experience.gui;

import javax.swing.JPanel;
import javax.swing.JRadioButton;

import pcgen.core.SettingsHandler;
import plugin.experience.ExperienceAdjusterPlugin;

/**
 *
 * @author  soulcatcher
 */
public class PreferencesExperiencePanel extends gmgen.gui.PreferencesPanel
{
	public static int EXPERIENCE_3 = 1;
	public static int EXPERIENCE_35 = 2;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup experienceGroup;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JPanel expPanel;
	private javax.swing.JRadioButton experienceRB1;
	private javax.swing.JRadioButton experienceRB2;
	private javax.swing.JScrollPane jScrollPane1;

	/** Creates new form PreferencesDamagePanel */
	public PreferencesExperiencePanel()
	{
		initComponents();
	}

	public void setExperience(int exp)
	{
		if (exp == EXPERIENCE_3)
		{
			experienceRB1.setSelected(true);
		}
		else if (exp == EXPERIENCE_35)
		{
			experienceRB2.setSelected(true);
		}
	}

	public int getExperience()
	{
		int returnVal = 0;

		if (experienceRB1.isSelected())
		{
			returnVal = EXPERIENCE_3;
		}
		else if (experienceRB2.isSelected())
		{
			returnVal = EXPERIENCE_35;
		}

		return returnVal;
	}

	public void applyPreferences()
	{
		SettingsHandler.setGMGenOption(ExperienceAdjusterPlugin.LOG_NAME + ".ExperienceType", getExperience());
	}

	public void initPreferences()
	{
		setExperience(SettingsHandler.getGMGenOption(ExperienceAdjusterPlugin.LOG_NAME + ".ExperienceType", EXPERIENCE_35));
	}

	public String toString()
	{
		return "Experience";
	}

	private void experienceAction(java.awt.event.ActionEvent evt)
	{
		 //GEN-FIRST:event_experienceAction

		// Add your handling code here:
	}
	 //GEN-LAST:event_experienceAction

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()
	{ //GEN-BEGIN:initComponents
		experienceGroup = new javax.swing.ButtonGroup();
		jScrollPane1 = new javax.swing.JScrollPane();
		mainPanel = new javax.swing.JPanel();
		expPanel = new javax.swing.JPanel();
		experienceRB1 = new javax.swing.JRadioButton();
		experienceRB2 = new javax.swing.JRadioButton();

		setLayout(new java.awt.BorderLayout());

		mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

		expPanel.setLayout(new javax.swing.BoxLayout(expPanel, javax.swing.BoxLayout.Y_AXIS));

		expPanel.setBorder(new javax.swing.border.TitledBorder(null, "Experience Calculation Type",
		        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
		        javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11)));
		experienceRB1.setSelected(true);
		experienceRB1.setText("Calculate total experience by party level, divide equally (3rd Ed, Modern)");
		experienceGroup.add(experienceRB1);
		experienceRB1.addActionListener(new java.awt.event.ActionListener()
			{
				public void actionPerformed(java.awt.event.ActionEvent evt)
				{
					experienceAction(evt);
				}
			});

		expPanel.add(experienceRB1);

		experienceRB2.setText("Calculate experience by individual PC level, divide total by number of PCs (3.5 Ed)");
		experienceGroup.add(experienceRB2);
		experienceRB2.addActionListener(new java.awt.event.ActionListener()
			{
				public void actionPerformed(java.awt.event.ActionEvent evt)
				{
					experienceAction(evt);
				}
			});

		expPanel.add(experienceRB2);

		mainPanel.add(expPanel);

		jScrollPane1.setViewportView(mainPanel);

		add(jScrollPane1, java.awt.BorderLayout.CENTER);
	}
	 //GEN-END:initComponents
}
