/*
 * InfoMisc.java
 * Copyright (c) 2001 Thomas G. W. Epperly <tomepperly@home.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * Created on April 22, 2001, 8:54 PM
 */

package pcgen.gui;

import java.awt.event.ComponentEvent;
import java.awt.event.FocusEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import pcgen.core.Globals;
import pcgen.core.PlayerCharacter;

/**
 * This displays three text areas for the user to provide information about
 * their companions, magic items and valuables (money, gems, and valuable
 * stuff).
 *
 * @deprecated  As of ver 3.1.2 moved all of this functionality into the notes in InfoDescription.java
 * @author  Tom Epperly
 * @version $Revision: 1.1 $
 */
final class InfoMisc extends JPanel
{

	private boolean d_shown = false;
	private JLabel d_moneyLabel;
	private JLabel d_magicLabel;
	private JLabel d_companionLabel;
	private JScrollPane d_magicArea;
	private JTextArea d_magicText;
	private JScrollPane d_moneyArea;
	private JTextArea d_moneyText;
	private JScrollPane d_companionArea;
	private JTextArea d_companionText;
	private static PlayerCharacter aPC = Globals.getCurrentPC();
	private static boolean needsUpdate = false;

	/** Creates new form InfoMisc */
	public InfoMisc()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the FormEditor.
	 */
	private void initComponents()
	{
		d_moneyLabel = new JLabel();
		d_magicLabel = new JLabel();
		d_companionLabel = new JLabel();
		d_magicArea = new JScrollPane();
		d_magicText = new JTextArea();
		d_moneyArea = new JScrollPane();
		d_moneyText = new JTextArea();
		d_companionArea = new JScrollPane();
		d_companionText = new JTextArea();

		setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		addComponentListener(new java.awt.event.ComponentAdapter()
		{
			public void componentShown(ComponentEvent evt)
			{
				formComponentShown(evt);
			}

			public void componentHidden(ComponentEvent evt)
			{
				sendDataToCore(evt);
			}
		});

		d_companionLabel.setText("Companions");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_companionLabel, gridBagConstraints1);

		d_moneyLabel.setText("Other Assets");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 2;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_moneyLabel, gridBagConstraints1);

		d_magicLabel.setText("Magic Items");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 4;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints1.weightx = 1.0;
		add(d_magicLabel, gridBagConstraints1);

		d_companionArea.setMinimumSize(new java.awt.Dimension(100, 64));
		d_companionText.setMinimumSize(new java.awt.Dimension(200, 64));
		d_companionText.addFocusListener(new java.awt.event.FocusAdapter()
		{
			public void focusLost(FocusEvent evt)
			{
				updateCoreCompanion(evt);
			}
		});

		d_companionArea.setViewportView(d_companionText);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 100.0;
		gridBagConstraints1.weighty = 1.0;
		add(d_companionArea, gridBagConstraints1);

		d_moneyArea.setMinimumSize(new java.awt.Dimension(100, 64));
		d_moneyText.setMinimumSize(new java.awt.Dimension(200, 64));
		d_moneyText.addFocusListener(new java.awt.event.FocusAdapter()
		{
			public void focusLost(FocusEvent evt)
			{
				updateCoreMoney(evt);
			}
		});

		d_moneyArea.setViewportView(d_moneyText);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 3;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 100.0;
		gridBagConstraints1.weighty = 1.0;
		add(d_moneyArea, gridBagConstraints1);

		d_magicArea.setMinimumSize(new java.awt.Dimension(100, 64));
		d_magicText.setMinimumSize(new java.awt.Dimension(200, 64));
		d_magicText.addFocusListener(new java.awt.event.FocusAdapter()
		{
			public void focusLost(FocusEvent evt)
			{
				updateCoreMagic(evt);
			}
		});

		d_magicArea.setViewportView(d_magicText);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 5;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints1.weightx = 100.0;
		gridBagConstraints1.weighty = 1.0;
		add(d_magicArea, gridBagConstraints1);
	}

	private void sendDataToCore(ComponentEvent evt)
	{
		if (aPC != null && d_shown)
		{
			String origText = (String)aPC.getMiscList().get(0);
			String newText = d_moneyText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(0, newText);
				aPC.setDirty(true);
			}
			origText = (String)aPC.getMiscList().get(1);
			newText = d_companionText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(1, newText);
				aPC.setDirty(true);
			}
			origText = (String)aPC.getMiscList().get(2);
			newText = d_magicText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(2, newText);
				aPC.setDirty(true);
			}
		}
	}

	private void formComponentShown(ComponentEvent evt)
	{
		requestFocus();
		PCGen_Frame1.getStatusBar().setText("");
		updateCharacterInfo();
	}

	public void updateCharacterInfo()
	{
		aPC = Globals.getCurrentPC();
		if (aPC == null)
			return;
		getDataFromCore();
		needsUpdate = false;
	}

	private void updateCoreMoney(FocusEvent evt)
	{
		if (!d_shown)
		{
			return;
		}
		final PlayerCharacter aPC = Globals.getCurrentPC();
		if (aPC != null)
		{
			final String origText = (String)aPC.getMiscList().get(0);
			final String newText = d_moneyText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(0, newText);
				aPC.setDirty(true);
			}
		}
	}

	private void updateCoreCompanion(FocusEvent evt)
	{
		if (!d_shown)
		{
			return;
		}

		final PlayerCharacter aPC = Globals.getCurrentPC();
		if (aPC != null)
		{
			final String origText = (String)aPC.getMiscList().get(1);
			final String newText = d_companionText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(1, newText);
				aPC.setDirty(true);
			}
		}
	}

	private void updateCoreMagic(FocusEvent evt)
	{
		if (!d_shown)
		{
			return;
		}
		final PlayerCharacter aPC = Globals.getCurrentPC();
		if (aPC != null)
		{
			final String origText = (String)aPC.getMiscList().get(2);
			final String newText = d_magicText.getText();
			if (!newText.equals(origText))
			{
				aPC.getMiscList().set(2, newText);
				aPC.setDirty(true);
			}
		}
	}

	private void getDataFromCore()
	{
		if (aPC != null)
		{
			final String currentMoney = (String)aPC.getMiscList().get(0);
			final String currentComp = (String)aPC.getMiscList().get(1);
			final String currentMagic = (String)aPC.getMiscList().get(2);
			if (!d_moneyText.getText().equals(currentMoney))
				d_moneyText.setText(currentMoney);
			if (!d_companionText.getText().equals(currentComp))
				d_companionText.setText(currentComp);
			if (!d_magicText.getText().equals(currentMagic))
				d_magicText.setText(currentMagic);
		}
		else
		{
			d_moneyText.setText("");
			d_companionText.setText("");
			d_magicText.setText("");
		}
		requestFocus();
		d_shown = true;
	}
}
