/* ============================================
 * JFreeChart : a free Java chart class library
 * ============================================
 *
 * Project Info:  http://www.object-refinery.com/jfreechart/index.html
 * Project Lead:  David Gilbert (david.gilbert@object-refinery.com);
 *
 * (C) Copyright 2000-2002, by Simba Management Limited and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * -----------------
 * ServletDemo1.java
 * -----------------
 * (C) Copyright 2002, by Simba Management Limited.
 *
 * Original Author:  David Gilbert (for Simba Management Limited);
 * Contributor(s):   -;
 *
 * $Id: ServletDemo1.java,v 1.1 2007/10/10 19:52:20 vauchers Exp $
 *
 * Changes:
 * --------
 * 14-Aug-2002 : Version 1 (DG);
 *
 */

package com.jrefinery.chart.demo;

import java.io.OutputStream;
import java.io.IOException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.ServletException;
import com.jrefinery.chart.JFreeChart;
import com.jrefinery.chart.ChartFactory;
import com.jrefinery.chart.ChartUtilities;
import com.jrefinery.data.CategoryDataset;

/**
 * A basic servlet that returns a PNG image file generated by JFreeChart.
 * <P>
 * This class is described in the JFreeChart Developer Guide.
 */
public class ServletDemo1 extends HttpServlet {

    /**
     * Default constructor.
     */
    public ServletDemo1() {
    }

    /**
     * Processes a GET request.
     *
     * @param request  The request.
     * @param response The response.
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        OutputStream out = response.getOutputStream();
        try {
            CategoryDataset data = DemoDatasetFactory.createCategoryDataset();
            JFreeChart chart = ChartFactory.createVerticalBarChart("Bar Chart",
                                                                   "Category",
                                                                   "Value",
                                                                   data,
                                                                   true);
            response.setContentType("image/png");
            ChartUtilities.writeChartAsPNG(out, chart, 400, 300);
        }
        catch (Exception e) {
            System.err.println(e.toString());
        }
        finally {
            out.close();
        }

    }

}
