/* ============================================
 * JFreeChart : a free Java chart class library
 * ============================================
 *
 * Project Info:  http://www.object-refinery.com/jfreechart/index.html
 * Project Lead:  David Gilbert (david.gilbert@object-refinery.com);
 *
 * (C) Copyright 2000-2002, by Simba Management Limited and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * -----------------
 * ServletDemo2.java
 * -----------------
 * (C) Copyright 2002, by Simba Management Limited.
 *
 * Original Author:  David Gilbert (for Simba Management Limited);
 * Contributor(s):   -;
 *
 * $Id: ServletDemo2.java,v 1.1 2007/10/10 19:52:20 vauchers Exp $
 *
 * Changes:
 * --------
 * 14-Aug-2002 : Version 1 (DG);
 *
 */

package com.jrefinery.chart.demo;

import java.io.PrintWriter;
import java.io.IOException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.ServletException;
import com.jrefinery.chart.JFreeChart;
import com.jrefinery.chart.ChartFactory;
import com.jrefinery.chart.ChartUtilities;
import com.jrefinery.data.CategoryDataset;

/**
 * A basic servlet that generates an HTML page that displays a chart generated by
 * JFreeChart.
 * <P>
 * This servlet uses another servlet (ServletDemo2ChartGenerator) to create a PNG image
 * for the embedded chart.
 * <P>
 * This class is described in the JFreeChart Developer Guide.
 */
public class ServletDemo2 extends HttpServlet {

    /**
     * Default constructor.
     */
    public ServletDemo2() {
    }

    /**
     * Processes a POST request.
     * <P>
     * The chart.html page contains a form for generating the first request, after that
     * the HTML returned by this servlet contains the same form for generating subsequent
     * requests.
     *
     * @param request  The request.
     * @param response The response.
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        PrintWriter out = new PrintWriter(response.getWriter());
        try {

            String param = request.getParameter("chart");

            response.setContentType("text/html");
            out.println("<HTML>");
            out.println("<HEAD>");
            out.println("<TITLE>JFreeChart Servlet Demo 2</TITLE>");
            out.println("</HEAD>");
            out.println("<BODY>");
            out.println("<H2>JFreeChart Servlet Demo</H2>");
            out.println("<P>");
            out.println("Please choose a chart type:");

            out.println("<FORM ACTION=\"ServletDemo2\" METHOD=POST>");
            String pieChecked = (param.equals("pie") ? " CHECKED" : "");
            String barChecked = (param.equals("bar") ? " CHECKED" : "");
            String timeChecked = (param.equals("time") ? " CHECKED" : "");
            out.println("<INPUT TYPE=\"radio\" NAME=\"chart\" VALUE=\"pie\""+pieChecked+"> Pie Chart");
            out.println("<INPUT TYPE=\"radio\" NAME=\"chart\" VALUE=\"bar\""+barChecked+"> Bar Chart");
            out.println("<INPUT TYPE=\"radio\" NAME=\"chart\" VALUE=\"time\""+timeChecked+"> Time Series Chart");
            out.println("<P>");
            out.println("<INPUT TYPE=\"submit\" VALUE=\"Generate Chart\">");
            out.println("</FORM>");

            out.println("<P>");
            out.println("<IMG SRC=\"ServletDemo2ChartGenerator?type="+param+"\" BORDER=1 WIDTH=400 HEIGHT=300/>");
            out.println("</BODY>");
            out.println("</HTML>");
            out.flush();
            out.close();
        }
        catch (Exception e) {
            System.err.println(e.toString());
        }
        finally {
            out.close();
        }

    }

}
